name: Code style

on: [push]

jobs:
  rustfmt:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            default: true
            target: wasm32-unknown-unknown
            components: rustfmt
      - name: Run cargo fmt
        run: cargo fmt -- --check

  clippy:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            default: true
            components: clippy
      - name: Run cargo check
        run: cargo clippy --features=quartz-runtime,unique-runtime,try-runtime,runtime-benchmarks --tests
        env:
          # We only need to check
          SKIP_WASM_BUILD: '1'
          # Has no sense in CI
          CARGO_INCREMENTAL: '0'
